import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Hand Talk",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning>
      <body>{children}</body>
    </html>
  );
}
